---
# Install Google Chrome
- name: "Does the Google apt file exist?"
  command: test -f {{ google_apt_file }}
  register: google_apt_exists
  ignore_errors: true

- name: "Add Google Chrome key"
  apt_key:
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: "Add Google Chrome repo"
  copy:
    content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    dest: '{{ google_apt_file }}'
    owner: root
    group: root
    mode: 644
  when: google_apt_exists.rc == 1

- name: "Update apt cache"
  apt:
    update_cache: yes
  when: google_apt_exists.rc == 1

- name: "Install Google Chrome"
  apt:
    name: google-chrome-stable
    state: latest
