---
# Install Nvidia driver
- name: "Looking for Nvidia hardware"
  command: /usr/bin/lspci | grep -i vga | grep -i nvidia
  register: nvidia_exists
  ignore_errors: true

- name: Ensure Nvidia apt repository
  apt_repository:
    repo: '{{ item }}'
    state: present
    update_cache: true
  with_items:
    - ppa:graphics-drivers/ppa
  when: nvidia_exists.rc == 0

- name: "Install Nvidia headless driver"
  apt:
    name:
      - nvidia-driver-430
      - nvidia-dkms-430
      - nvidia-headless-430
      - nvidia-headless-no-dkms-430
      - nvidia-utils-430
      - nvidia-common
    state: latest
  when: nvidia_exists.rc == 0
