---
# Install slack-desktop
- name: "Does the slack-desktop apt file exist?"
  command: test -f {{ slack_desktop_apt_file }}
  register: slack_desktop_apt_exists
  ignore_errors: true

- name: "Add slask-desktop key"
  apt_key:
    id: '{{ item.id }}'
    url: '{{ item.url }}'
    state: present
  with_items:
    - { url: 'https://slack.com/gpg/slack_pubkey.gpg', id: '7253C9C8BF6A7041' }
    - { url: 'https://packagecloud.io/slacktechnologies/slack/gpgkey', id: 'C6ABDCF64DB9A0B2' }

- name: "Add slack-desktop repo"
  copy:
    content: "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
    dest: '{{ slack_desktop_apt_file }}'
    owner: root
    group: root
    mode: 644
  when: slack_desktop_apt_exists.rc == 1

- name: "Update apt cache"
  apt:
    update_cache: yes
  when: slack_desktop_apt_exists.rc == 1

- name: "Install slack-desktop"
  apt:
    name: slack-desktop
    state: latest
